substitutions:
  device_name: snp_hsp_1
  device_fallback_ap_password: !secret hsp_device_fallback_ap_password
  device_api_password: !secret hsp_device_api_password
  device_ota_password: !secret hsp_device_ota_password
  wifi_ssid: !secret home_wifi_ssid
  wifi_password: !secret home_wifi_password

packages:
  base: !include includes/wemos_d1_base.yaml
  wifi: !include includes/wifi_common.yaml
  device_common: !include includes/device_common.yaml


sensor:
  - platform: dht
    model: AM2302
    pin:
      number: D2
      mode: INPUT_PULLUP
    temperature:
      name: "Entertainment Cabinet Temperature"
      device_class: temperature
    humidity:
      name: "Entertainment Cabinet Humidity"
      device_class: humidity
    update_interval: 60s


output:
  platform: esp8266_pwm
  pin: D3
  frequency: 25000 Hz
  id: pwm_output

fan:
  platform: speed
  output: pwm_output
  name: "Entertainment Cabinet Ventilation"
