substitutions:
  device_name: snp_hbt_1
  device_fallback_ap_password: !secret hbt_device_fallback_ap_password
  device_api_password: !secret hbt_device_api_password
  device_ota_password: !secret hbt_device_ota_password
  wifi_ssid: !secret home_wifi_ssid
  wifi_password: !secret home_wifi_password

packages:
  base: !include includes/feather_esp32_base.yaml
  wifi: !include includes/wifi_common.yaml
  device_common: !include includes/device_common.yaml

light:
  - platform: fastled_clockless
    chipset: NEOPIXEL
    pin: GPIO32
    num_leds: 32
    name: "Adafruit NeoPixel FeatherWing"
    effects:
      - addressable_rainbow:
          name: Happy Effect
          speed: 10
      - addressable_twinkle:
          name: Twinkle Effect
          twinkle_probability: 5%

sensor:
  - platform: adc
    pin: A13
    name: "Battery Voltage"
    update_interval: 60s
    attenuation: 11db
    filters:
      - multiply: 2
