substitutions:
  device_name: snp-splug-2
  device_fallback_ap_password: !secret basement_smartplug_2_fallback_ap_password
  device_api_password: !secret basement_smartplug_2_api_password
  device_ota_password: !secret basement_smartplug_2_ota_password
  wifi_ssid: !secret home_wifi_ssid
  wifi_password: !secret home_wifi_password

packages:
  base: !include includes/sonoff-s31-base.yaml
  wifi: !include includes/wifi_common.yaml
  device_common: !include includes/device_common.yaml
